# GENERATED by scripts/update-homebrew-formula.sh -- do not edit by hand.
#
# Regenerated by the release workflow for every published version, so this
# file cannot describe a release that does not exist (#501).
class Doiget < Formula
  desc "Open Access paper fetcher with an MCP server"
  homepage "https://github.com/QAtlasHub/doiget"
  version "0.8.12"
  license "MIT"

  # The published binaries are the release assets themselves, not archives, so
  # each URL is fetched verbatim. They are statically linked (musl on Linux),
  # which is why there are no dependencies to declare.
  on_macos do
    on_arm do
      url "https://github.com/QAtlasHub/doiget/releases/download/v0.8.12/doiget-macos-aarch64"
      sha256 "8aa163dba6c34527ae4ce819835aa138779fdad5041236830ae8833ad18b51cf"
    end
    on_intel do
      url "https://github.com/QAtlasHub/doiget/releases/download/v0.8.12/doiget-macos-x86_64"
      sha256 "caabe258798c9b10f53d3f4238e233e8daa3060596b05bed740e591224f10c5f"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/QAtlasHub/doiget/releases/download/v0.8.12/doiget-linux-x86_64"
      sha256 "e22c603447b1a2bc9b7c8cf9616085e789334541c6611e368e69aa2333fa61a5"
    end
  end

  def install
    # One asset per platform, whichever was downloaded.
    bin.install Dir["doiget-*"].first => "doiget"
  end

  test do
    assert_match "doiget #{version}", shell_output("#{bin}/doiget --version")
  end
end
