# GENERATED by scripts/update-homebrew-formula.sh -- do not edit by hand.
#
# Regenerate with `scripts/update-homebrew-formula.sh <version>` after a stable
# release has published its assets. That is a MAINTAINER step, not a workflow
# step -- committing the formula back from CI needs a token with write access
# to a protected branch, and #426 says that token is broken. So the formula
# lags the tag until someone runs the script, and CONTRIBUTING.md says so
# (#501).
class Doiget < Formula
  desc "Open Access paper fetcher with an MCP server"
  homepage "https://github.com/QAtlasHub/doiget"
  version "0.8.13"
  license "MIT"

  # The published binaries are the release assets themselves, not archives, so
  # each URL is fetched verbatim. They are statically linked (musl on Linux),
  # which is why there are no dependencies to declare.
  on_macos do
    on_arm do
      url "https://github.com/QAtlasHub/doiget/releases/download/v0.8.13/doiget-macos-aarch64"
      sha256 "7daa6b22fabd726d6e707887375da1eab750c53ef63554523c7403b5badb34fc"
    end
    on_intel do
      url "https://github.com/QAtlasHub/doiget/releases/download/v0.8.13/doiget-macos-x86_64"
      sha256 "17c7e3d733b446ab7186794020b0692dae0886cc5edaad455565924e602d4c1c"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/QAtlasHub/doiget/releases/download/v0.8.13/doiget-linux-x86_64"
      sha256 "4e6a4d09c6bf4056cb02f64bfeb6e2c71340b80646e6f3afeef4b39557806680"
    end
  end

  def install
    # One asset per platform, whichever was downloaded.
    bin.install Dir["doiget-*"].first => "doiget"
  end

  test do
    assert_match "doiget #{version}", shell_output("#{bin}/doiget --version")
  end
end
