#!/usr/bin/env bash
# Regenerate Formula/doiget.rb for a released version (#501).
#
# The formula is GENERATED, never hand-edited: #247 was closed as completed
# while four fifths of it had not shipped, and a hand-maintained formula is
# exactly the kind of thing that half-lands the same way. The release workflow
# runs this, so the formula cannot describe a version that was never published.
#
# Usage:
#   scripts/update-homebrew-formula.sh <version>
#   scripts/update-homebrew-formula.sh <version> <sha_macos_arm> <sha_macos_x86> <sha_linux_x86>
#
# With only a version, the checksums are read from that release's published
# `.sha256` assets -- the same files the curl installer verifies against, so
# the formula cannot disagree with the binary it installs. The four-argument
# form exists so the generator can be tested without a network.
set -euo pipefail

VERSION="${1:?usage: update-homebrew-formula.sh <version> [sha_arm sha_x86 sha_linux]}"
REPO="${DOIGET_REPO:-QAtlasHub/doiget}"
OUT="${DOIGET_FORMULA_OUT:-Formula/doiget.rb}"

# A leading `v` is how the tag is written and NOT how the formula version is;
# accept either and normalise, so a caller passing the tag is not silently
# wrong.
VERSION="${VERSION#v}"

fetch_sha() {
  local asset="$1"
  # `.sha256` files are `<hex>  <name>`; take the first field.
  curl --proto '=https' --tlsv1.2 -fsSL \
    "https://github.com/${REPO}/releases/download/v${VERSION}/${asset}.sha256" \
    | awk '{print $1; exit}'
}

if [ "$#" -ge 4 ]; then
  SHA_ARM="$2"; SHA_X86="$3"; SHA_LINUX="$4"
else
  SHA_ARM="$(fetch_sha doiget-macos-aarch64)"
  SHA_X86="$(fetch_sha doiget-macos-x86_64)"
  SHA_LINUX="$(fetch_sha doiget-linux-x86_64)"
fi

for pair in "SHA_ARM:$SHA_ARM" "SHA_X86:$SHA_X86" "SHA_LINUX:$SHA_LINUX"; do
  name="${pair%%:*}"; val="${pair#*:}"
  if ! printf '%s' "$val" | grep -qE '^[0-9a-f]{64}$'; then
    echo "::error::update-homebrew-formula: $name is not a sha256: '$val'" >&2
    exit 1
  fi
done

mkdir -p "$(dirname "$OUT")"
cat > "$OUT" <<RUBY
# GENERATED by scripts/update-homebrew-formula.sh -- do not edit by hand.
#
# Regenerated by the release workflow for every published version, so this
# file cannot describe a release that does not exist (#501).
class Doiget < Formula
  desc "Open Access paper fetcher with an MCP server"
  homepage "https://github.com/${REPO}"
  version "${VERSION}"
  license "MIT"

  # The published binaries are the release assets themselves, not archives, so
  # each URL is fetched verbatim. They are statically linked (musl on Linux),
  # which is why there are no dependencies to declare.
  on_macos do
    on_arm do
      url "https://github.com/${REPO}/releases/download/v${VERSION}/doiget-macos-aarch64"
      sha256 "${SHA_ARM}"
    end
    on_intel do
      url "https://github.com/${REPO}/releases/download/v${VERSION}/doiget-macos-x86_64"
      sha256 "${SHA_X86}"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/${REPO}/releases/download/v${VERSION}/doiget-linux-x86_64"
      sha256 "${SHA_LINUX}"
    end
  end

  def install
    # One asset per platform, whichever was downloaded.
    bin.install Dir["doiget-*"].first => "doiget"
  end

  test do
    assert_match "doiget #{version}", shell_output("#{bin}/doiget --version")
  end
end
RUBY

echo "wrote $OUT for v${VERSION}"
